yotta_unit:
    items:
        security: 
            type: "bundle"      # widget | system
            name: "Security"
            description: "Security manager"
            icon: "security" # optional
            version: "0.1"    # optional
            # if bundle | widget
            entry_point: "/bundles/yottasecurity/build/js/index.js" # path to entry point
            # developer: 1    # optional

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: YottaCms\Bundle\YottaSecurityBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~
            form_login:
                provider: fos_userbundle
    
doctrine:
    dbal:
        driver: 'pdo_mysql'
        charset: utf8mb4
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
